apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recommendation-api
  template:
    metadata:
      labels:
        app: recommendation-api
    spec:
      containers:
        - name: recommendation-api
          image: sumanth17121988/recommendation-api-demo:1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-api-service
spec:
  selector:
    app: recommendation-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer